### PR TITLE
Update web3.md

### PR DESCRIPTION
**Pull request by Alonski**
More grammer and spelling fixes

### CODE REVIEW

**Comment by andytudhope** [comment]
Hi @Alonski! Please don't make multiple PRs for simple grammar fixes with only one change per PR. Thank you so much for going through and doing these grammar changes, but please do them all in one hit as it is just easier to manage our commit history that way.

**Comment by Alonski** [comment]
Ok I will close the other branch.
I will leave this open for today while I go over and you can pull this in tomorrow 😄

**Comment by Alonski** [comment]
Hey @andytudhope I kind of forgot about this. Should this be merged or closed?

**Comment by andytudhope** [comment]
Hey @Alonski - we're not really using this repo much anymore, we should prob just close it.

**Pull request closed without merging**
